version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['un', 'deux', 'trois']

  - name: enfr
    description: "EN to FR"
    columns:
      - name: EN
        tests:
          - relationships:
              to: ref('ende')
              field: EN
