
version: 2

models:

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['un', 'deux', 'trois']  # this should fail due to 'troi'

  - name: enfr
    description: "EN to FR"
    columns:
      - name: EN
        tests:
          - relationships:
              to: ref('ende')
              field: EN
