name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"] # let's bump these up to ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-venv make

      - name: Install dependencies
        run: |
         bash -c "make update"

      - name: Debug Tests Directory
        run: |
          echo "Checking tests directory..."
          ls -R tests || echo "Tests directory not found!"

      - name: Test with pytest
        run: |
          make test
