
name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Set Correct Working Directory
        run: |
          cd $GITHUB_WORKSPACE
          echo "Corrected working directory: $(pwd)"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-venv

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m venv env
          source env/bin/activate
          python3 -m ensurepip --default-pip
          $GITHUB_WORKSPACE/env/bin/python -m pip install --upgrade pip
          $GITHUB_WORKSPACE/env/bin/python -m pip install -r scripts/requirements.txt

      - name: Debug Virtual Environment
        run: |
          echo "Python binary: $(which python)"
          echo "Pip binary: $(which pip)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE/env/bin/

      - name: Run OS and Python version tests
        run: |
          $GITHUB_WORKSPACE/env/bin/python -m pytest tests/test_system.py

      - name: Test with pytest
        run: |
          $GITHUB_WORKSPACE/env/bin/python -m pytest -vvx tests
