name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-venv

      - name: Install dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m ensurepip --default-pip  # Ensures pip is available
          pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run OS and Python version tests
        run: |
          env/bin/python -m pytest tests/test_system.py

      - name: Test with pytest
        run: |
          env/bin/python -m pytest -vvx tests
